# Generated by Django 5.1 on 2024-09-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('clinic_id', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_mobile', models.CharField(max_length=15)),
                ('notes_by_admin', models.TextField(blank=True, null=True)),
                ('notes_by_neuroscientist', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
